### ISSUE TITLE
Bug while installing recent release

### ISSUE THREAD

**Issue by vanadium23** [menezes-/pystalkd#9]
After you've bumped a new version to a pypi, there is a bug, that i can't install package without globally installed pandoc.
```
  Using cached pystalkd-1.2.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q2wn0a3r/pystalkd/setup.py", line 10, in <module>
        process = subprocess.Popen(['pandoc', '--from=markdown', "--to=rst", "README.md"], stdout=subprocess.PIPE)
      File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'pandoc'
```

**Comment by menezes-** [comment]
@vanadium23  sorry! Fixed version is on pypi already
